### ISSUE TITLE
Failed to resolve import @morev/vue-transitions/styles using Nuxt 3

### ISSUE THREAD

**Issue by r0lodex** [MorevM/vue-transitions#254]
### Actual behavior

When building, throws error

```bash
Failed to resolve import "@morev/vue-transitions/styles" from "virtual:nuxt:/app/.nuxt/css.mjs". Does the file exist?
```

### Expected behavior

Should've resolved the import

### Steps to reproduce

- Added the package with `bun add @morev/vue-transitions/nuxt`
- Added into Nuxt's modules

```
// nuxt.config.ts
modules: [
    ...
    "@morev/vue-transitions/nuxt",
  ],
```

- Use it is any of view files e.g Test.vue

```
<TransitionSlide :offset="[-16, 0]">
    content
</TransitionSlide>
```

### Environment

- Device: 2019 16" MBP (Intel)
- OS: Sonoma 14.2

### Possible solution

Possibly updating the package to have the styles imported properly.

**Comment by MorevM** [comment]
Good day @r0lodex, 

What version of Nuxt are you using?
Currently the module works fine (well, there are still some issues like types resolution and couple of bugs..) in my environment (Windows, any Nuxt@^2.x.x and Nuxt@3.6.4), maybe something went wrong because of using Bun or with Nuxt upgrade to version more than 3.6.4 - they have some Windows issues so I can't upgrade right now to test.

I'll try to take a look with Bun. Anyway, please provide more info about your environment - it might help. 

For now, I believe it is possible to use the package as a custom Nuxt plugin and import stylesheet directly, I wrote about it [here](https://github.com/MorevM/vue-transitions?tab=readme-ov-file#global-registration).

**Comment by r0lodex** [comment]
Thank you for responding. I'm using Nuxt 3.8.1 on MacOS Sonoma 14.2
I'll try on my end with npm or yarn. 

Cheers and thank you again

**Comment by r0lodex** [comment]
I just read that you have a postinstall npm hook and that might be the reason it doesn't work with `bun`.
I've tried with `npm` and `yarn` and it works fine.

**Comment by r0lodex** [comment]
For `bun` users — https://bun.sh/guides/install/trusted

**Comment by Jarred-Sumner** [comment]
As of Bun v1.0.17, the top 500 npm packages that use postinstall scripts are now run by default. Please try again with Bun v1.0.17 and let me know if you still run into this.

**Comment by MorevM** [comment]
@Jarred-Sumner well, I don't believe this package will ever be in the top 500 :D

@r0lodex does it work fine if you specify the package in `trustedDependencies`?
I would write about it in the readme file

**Comment by fahdlaabi** [comment]
@MorevM I tried the `trustedDependencies` field & it works, thank's!

**Comment by MorevM** [comment]
I wrote a note about [usage with Bun](https://github.com/MorevM/vue-transitions?tab=readme-ov-file#using-bun).
Thank you guys for pointing that out :)
