### ISSUE TITLE
Nuxt Error: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by BayBreezy** [MorevM/vue-transitions#268]
### Actual behavior

It would seem as though something broke in the last update I made. My apologies.
I keep getting this error in a Nuxt 3 project
`Cannot read properties of undefined (reading '_c')`

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/9e907390-2b87-424f-8683-84eef1ebda22">

### Expected behavior

For the Transition components to work as usual.

### Steps to reproduce

1. Create a Nuxt 3 project
2. Install the package
3. Use one of the components

### Environment

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      default

### Additional context

This is an image of the structure created with the new version. It looks correct.

<img width="306" alt="image" src="https://github.com/user-attachments/assets/3ead3d64-1a1e-4e35-8e38-49f0b9531a0d">

When I build locally and test locally I now get this error 
<img width="778" alt="image" src="https://github.com/user-attachments/assets/f2cc93ac-8ab9-421d-82c1-40b49ce72168">

Even after I downgrade to the version that `@morev/utils` was before which was 3.7, I still experience this error.

Any help would be great with this. Just point me to what you think may be the fix and I can implement it.

### Possible solution

I am thinking it has something to do with how another package is transpiled(or not)

**Comment by MorevM** [comment]
Good day @BayBreezy 

Thanks for noticing - as said, I'm working on other things in a different environment right now and was too lazy to check the actual functionality since the diff looked safe.

There's nothing wrong with your code - it's my mistake. 
I decided to fix an old issue at the same time (#265) and inadvertently broke a script that, after installation, detects the Vue version and sets Vue2/Vue3 version of components as the main one (they use different builders).

This is fixed in 3.0.5 (I checked on different environment) :)

**Comment by BayBreezy** [comment]
Oh. Ok. Thanks.  I was a bit worried there 😆

**Comment by matthew-dean** [comment]
This has actually been happening to me for a long time, and I haven't been able to figure it out. First, it happened all the time when I did a Nuxt production build that I served with a simple web server. So I used a different web server. But _now_ after the latest Nuxt upgrade I did, this is happening now _all_ the time, even in the dev server. What's the secret sauce for why that particular section of the code keeps breaking? For me, it's right here:
```
TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (vue-transitions.js:544:22)

var render = function() {
  var _vm = this;
  var _h = _vm.$createElement;
  var _c = _vm._self._c || _h; // in this line, `_self` is undefined
```

**Comment by matthew-dean** [comment]
Okay, finally! I drilled through the documentation and finally figured out that there is a separate export like: `'@morev/vue-transitions/vue3'`. I used that and it solved the issue! (Not sure why it didn't work automatically with Nuxt before.)

Incidentally, there are tools that will allow you to create "universal" Vue 2/3 components so you don't have to try to auto-install the right one.

**Comment by MorevM** [comment]
@matthew-dean 

Something like `vue-demi` won't work here, as Vue 3 requires explicit import of the `Transition` and `TransitionGroup` components, whereas Vue 2 allows to just refer globally by the name, e.g. `<component is="transition">`, whereas this doesn't work in Vue 3.

Maybe your issue is related to the bundler (bun? pnpm?), it might make sense to explicitly run the `vue-transitions-version-switch 3` command after the build, before running in the container.

For me, it might make sense to release the next major version of the project exclusively for Vue 3, since Vue 2 reached EOL already two years ago and there is no point in maintaining it anymore (the current 3.x branch at least works fine).

I'm busy with other things right now, but will try to find time in the near future
